configuration:
  arguments:
    todoId: "1"
    myVar: "world"
flows:
  default:
    - task: http
      in:
        url: "https://jsonplaceholder.typicode.com/todos/${todoId}"
        response: json
        out: myTodo

    - if: "${myTodo.content.completed}"
      then:
        - log: "All done!"
      else:
        - log: "You got a todo item: ${myTodo.content.title}"
  onPush:
    - log: "alert('OK')"
 
triggers:
- github:
    useInitiator: true
    entryPoint: onPush
    conditions:
      type: push