configuration:
  arguments:
    todoId: "1"
    myVar: "world"
flows:
  default:
    - task: http
      in:
        url: "https://jsonplaceholder.typicode.com/todos/${todoId}"
        response: json
        out: myTodo

    - if: "${myTodo.content.completed}"
      then:
        - log: "All done!"
      else:
        - task: http
          in:
            request: json
            method: POST
            url: "https://prod-29.westus.logic.azure.com/workflows/cb8555e85d78488a8f489c41bc614de6/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=siUPJPKiRBUmFhDJy1JoUg0N4ry1C9vaHApJwQ8zvaE"
            body:
              userObj:
                name: concord
            response: json
            out: response
        - if: ${response.success}
          then:
          - log: "Response received: ${response.content}"
  onPush:
    - log: "alert('OK')"
 
triggers:
- github:
    useInitiator: true
    entryPoint: onPush
    conditions:
      type: push