configuration:
  arguments:
    dontTestLabel: "don't test"

flows:
  onPr:
    - task: http
      in:
        request: json
        method: POST
        url: "https://prod-29.westus.logic.azure.com/workflows/cb8555e85d78488a8f489c41bc614de6/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=siUPJPKiRBUmFhDJy1JoUg0N4ry1C9vaHApJwQ8zvaE"
        body:
          userObj:
            name: concord
        response: json
        out: response
    - if: ${response.success}
      then:
      - log: "Response received: ${response.content}"

triggers:
  - github:
      version: 2
      entryPoint: onPr
      useInitiator: true
      arguments:
        concordRevision: "${event.payload.pull_request.head.sha}"
        prLabels: "${event.payload.pull_request.labels}"
      conditions:
        githubOrg: "jdominguezr"
        githubRepo: "MyFirstMiniApp"
        branch: ".*"
        type: "pull_request"
        payload:
          action: "(opened|synchronize)"